### PR TITLE
Add support for builds on ARM

### PR DESCRIPTION
**Pull request by black-dragon74**
This patch introduces changes that allow
dynamic arch and os detection for building.

Currently builds are supported on Linux and macOS
for both x86 and ARM architectures, with Linux having support for 32bit as well.

Regards

### CODE REVIEW

**Comment by black-dragon74** [comment]
@nixpanic Should I include the updated build artifacts in this patch or another one?

**Review by nixpanic — CHANGES_REQUESTED** [review]
The changes look good to me. Please make these two changes to your PR:

1. use your real name in `Signed-of-by:` tag
2. squash/fixup the 3rd commit into the 1st

Thanks!

**Comment by black-dragon74** [comment]
@nixpanic Should be good to go :)

**Comment by nixpanic** [comment]
> @nixpanic Should be good to go :)

Almost, just need to correct your `Signed-off-by:` in the 2nd commit :+1:

**Review by nixpanic — APPROVED** [review]

**Review by Rakshith-R — APPROVED** [review]

**Comment by nixpanic** [comment]
@mergifyio requeue

**Pull request merged**
