### PR TITLE
the cidr should be a list of strings 

### PR DESCRIPTION
**Pull request by Yuggupta27**
currently, the helper functions will return a reference
to another data type CIDR which return the value of type
`*[]CIDR`; but we would prefer a list of strings
`[]string`.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@Yuggupta27 i don't see any problem with having an array of *[]CIDS what is the exact problem you are facing because of this one?

**Comment by Yuggupta27** [comment]
> @Yuggupta27 i don't see any problem with having an array of *[]CIDS what is the exact problem you are facing because of this one?

We just have a fixed format for CIDR blocks(list of strings). Although a separate message for CIDR increases modularity, it increases complexity too.

```
type CIDR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CIDR block
	Cidr string `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
}
```
Here, we just require just the string.

I am also fine with sticking with the current approach, as the CIDR can still be fetched by:
```
cidrs := req.GetCidrs()
cidr := cidrs[0]
cidrs := cidr.Cidr
```

Let me know what you think?

**Comment by Madhu-1** [comment]
IMO the above is fine. its increases modularity and CIRD will have its own identity.

**Comment by Yuggupta27** [comment]
Thanks for the suggestion! Closing this PR.

**Pull request closed without merging**
