### PR TITLE
doc: correct type description

### PR DESCRIPTION
**Pull request by Yuggupta27**
correct UNKNOWN type description

Signed-off-by: Yug Gupta <yuggupta27@gmail.com>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]

**Review by nixpanic — APPROVED** [review]

**Review by nixpanic — CHANGES_REQUESTED** [review]
Actually, the generated protoc file and API should be updated too!

**Comment by Madhu-1** [comment]
@mergifyio rebase

**Comment by nixpanic** [comment]
For some reason the `protoc` test does not return an error, although it logs one at https://github.com/csi-addons/spec/runs/4578605775?check_suite_focus=true#step:3:296 :
```
files got changed exit 1
```
Because the README updates a comment inside the generated `.protoc` file, the `.go` files need to be regenerated too as they contain the comments as well.

**Comment by nixpanic** [comment]
> For some reason the `protoc` test does not return an error, although it logs one at https://github.com/csi-addons/spec/runs/4578605775?check_suite_focus=true#step:3:296 :
> 
> ```
> files got changed exit 1
> ```
> 
> Because the README updates a comment inside the generated `.protoc` file, the `.go` files need to be regenerated too as they contain the comments as well.

This is addressed in the CI job with #36.

**Comment by Madhu-1** [comment]
@mergifyio  rebase

**Comment by Madhu-1** [comment]
@Mergifyio rebase

**Comment by Yuggupta27** [comment]
> Actually, the generated protoc file and API should be updated too!

Thanks for the suggestion! Added the generated files too :+1:

**Review by nixpanic — APPROVED** [review]

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
